version: "3.9"

services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
      - mern-app

  server:
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - mern-app
    depends_on:
      - mongodb
    environment:
      - PORT=8000
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY=AKIAX64RC3P5FXTHO37U
      - AWS_SECREAT_KEY=p6PEhdPdDRjTv0JLhhrSPX+malQjyEzhJbfowM6F
      - S3_BUCKET_NAME=ds-nature-ayur
      - MONGOURL=mongodb+srv://Heshan:Heshan123@cluster0.dyyifxu.mongodb.net/naturaayur?retryWrites=true&w=majority
      - JWT_SECRET=NAtureAyut2023LLcC
      - JWT_REFRESH_TOKEN=NAtureAyut2023LLcCREFRERESH
      - ADMIN_MAIL=natureayure@gmail.com
      - ADMIN_MAILAPP_PASSWORD=jtkgrcvpkpsjvuho
      - FRONTEND=http://localhost:3000
      - PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51Mud2bCdnivczi88IyelFBlmNOwCywXQWsUYbDCc7XjISenCaElNJjY3K4QAEWO50wdKFWgYJRIjUgHPKbcaB9T500SIdlAVHS
      - PUBLIC_STRIPE_SECRET_KEY=sk_test_51Mud2bCdnivczi886NjEi2yULVgdkuTqhbyYIqKBHTKmpuwWQGbJN6fTEOa5szpIcK9po23NuEAd4HySXIEykXkc00qsg3WyWh
      - PUBLIC_STRIPE_WEBHOOK_SECRET_KEY=whsec_9580fde0829c6d8586cebfd04aa12f398b20806b07517da5b21e6776f61fff01

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - mern-app

  gateway:
    build: ./backend/api_gateway
    ports:
      - "8001:8001"
    networks:
      - mern-app
    depends_on:
      - frontend
    environment:
      - PORT=8001
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY=AKIAX64RC3P5FXTHO37U
      - AWS_SECREAT_KEY=p6PEhdPdDRjTv0JLhhrSPX+malQjyEzhJbfowM6F
      - S3_BUCKET_NAME=ds-nature-ayur
      - MONGOURL=mongodb+srv://Heshan:Heshan123@cluster0.dyyifxu.mongodb.net/naturaayur?retryWrites=true&w=majority
      - JWT_SECRET=NAtureAyut2023LLcC
      - JWT_REFRESH_TOKEN=NAtureAyut2023LLcCREFRERESH
      - ADMIN_MAIL=natureayure@gmail.com
      - ADMIN_MAILAPP_PASSWORD=jtkgrcvpkpsjvuho
      - FRONTEND=http://localhost:3000
      - PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51Mud2bCdnivczi88IyelFBlmNOwCywXQWsUYbDCc7XjISenCaElNJjY3K4QAEWO50wdKFWgYJRIjUgHPKbcaB9T500SIdlAVHS
      - PUBLIC_STRIPE_SECRET_KEY=sk_test_51Mud2bCdnivczi886NjEi2yULVgdkuTqhbyYIqKBHTKmpuwWQGbJN6fTEOa5szpIcK9po23NuEAd4HySXIEykXkc00qsg3WyWh
      - PUBLIC_STRIPE_WEBHOOK_SECRET_KEY=whsec_9580fde0829c6d8586cebfd04aa12f398b20806b07517da5b21e6776f61fff01

  auth:
    build: ./backend/auth
    ports:
      - "8002:8002"
    networks:
      - mern-app
    depends_on:
      - frontend
    environment:
      - PORT=8002
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY=AKIAX64RC3P5FXTHO37U
      - AWS_SECREAT_KEY=p6PEhdPdDRjTv0JLhhrSPX+malQjyEzhJbfowM6F
      - S3_BUCKET_NAME=ds-nature-ayur
      - MONGOURL=mongodb+srv://Heshan:Heshan123@cluster0.dyyifxu.mongodb.net/naturaayur?retryWrites=true&w=majority
      - JWT_SECRET=NAtureAyut2023LLcC
      - JWT_REFRESH_TOKEN=NAtureAyut2023LLcCREFRERESH
      - ADMIN_MAIL=natureayure@gmail.com
      - ADMIN_MAILAPP_PASSWORD=jtkgrcvpkpsjvuho
      - FRONTEND=http://localhost:3000
      - PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51Mud2bCdnivczi88IyelFBlmNOwCywXQWsUYbDCc7XjISenCaElNJjY3K4QAEWO50wdKFWgYJRIjUgHPKbcaB9T500SIdlAVHS
      - PUBLIC_STRIPE_SECRET_KEY=sk_test_51Mud2bCdnivczi886NjEi2yULVgdkuTqhbyYIqKBHTKmpuwWQGbJN6fTEOa5szpIcK9po23NuEAd4HySXIEykXkc00qsg3WyWh
      - PUBLIC_STRIPE_WEBHOOK_SECRET_KEY=whsec_9580fde0829c6d8586cebfd04aa12f398b20806b07517da5b21e6776f61fff01

  orders:
    build: ./backend/orders
    ports:
      - "8003:8003"
    networks:
      - mern-app
    depends_on:
      - frontend
    environment:
      - PORT=8003
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY=AKIAX64RC3P5FXTHO37U
      - AWS_SECREAT_KEY=p6PEhdPdDRjTv0JLhhrSPX+malQjyEzhJbfowM6F
      - S3_BUCKET_NAME=ds-nature-ayur
      - MONGOURL=mongodb+srv://Heshan:Heshan123@cluster0.dyyifxu.mongodb.net/naturaayur?retryWrites=true&w=majority
      - JWT_SECRET=NAtureAyut2023LLcC
      - JWT_REFRESH_TOKEN=NAtureAyut2023LLcCREFRERESH
      - ADMIN_MAIL=natureayure@gmail.com
      - ADMIN_MAILAPP_PASSWORD=jtkgrcvpkpsjvuho
      - FRONTEND=http://localhost:3000
      - PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51Mud2bCdnivczi88IyelFBlmNOwCywXQWsUYbDCc7XjISenCaElNJjY3K4QAEWO50wdKFWgYJRIjUgHPKbcaB9T500SIdlAVHS
      - PUBLIC_STRIPE_SECRET_KEY=sk_test_51Mud2bCdnivczi886NjEi2yULVgdkuTqhbyYIqKBHTKmpuwWQGbJN6fTEOa5szpIcK9po23NuEAd4HySXIEykXkc00qsg3WyWh
      - PUBLIC_STRIPE_WEBHOOK_SECRET_KEY=whsec_9580fde0829c6d8586cebfd04aa12f398b20806b07517da5b21e6776f61fff01

  products:
    build: ./backend/products
    ports:
      - "8004:8004"
    networks:
      - mern-app
    depends_on:
      - frontend
    environment:
      - PORT=8004
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY=AKIAX64RC3P5FXTHO37U
      - AWS_SECREAT_KEY=p6PEhdPdDRjTv0JLhhrSPX+malQjyEzhJbfowM6F
      - S3_BUCKET_NAME=ds-nature-ayur
      - MONGOURL=mongodb+srv://Heshan:Heshan123@cluster0.dyyifxu.mongodb.net/naturaayur?retryWrites=true&w=majority
      - JWT_SECRET=NAtureAyut2023LLcC
      - JWT_REFRESH_TOKEN=NAtureAyut2023LLcCREFRERESH
      - ADMIN_MAIL=natureayure@gmail.com
      - ADMIN_MAILAPP_PASSWORD=jtkgrcvpkpsjvuho
      - FRONTEND=http://localhost:3000
      - PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51Mud2bCdnivczi88IyelFBlmNOwCywXQWsUYbDCc7XjISenCaElNJjY3K4QAEWO50wdKFWgYJRIjUgHPKbcaB9T500SIdlAVHS
      - PUBLIC_STRIPE_SECRET_KEY=sk_test_51Mud2bCdnivczi886NjEi2yULVgdkuTqhbyYIqKBHTKmpuwWQGbJN6fTEOa5szpIcK9po23NuEAd4HySXIEykXkc00qsg3WyWh
      - PUBLIC_STRIPE_WEBHOOK_SECRET_KEY=whsec_9580fde0829c6d8586cebfd04aa12f398b20806b07517da5b21e6776f61fff01

  reviews:
    build: ./backend/reviews
    ports:
      - "8005:8005"
    networks:
      - mern-app
    depends_on:
      - mongodb
    environment:
      - PORT=8005
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY=AKIAX64RC3P5FXTHO37U
      - AWS_SECREAT_KEY=p6PEhdPdDRjTv0JLhhrSPX+malQjyEzhJbfowM6F
      - S3_BUCKET_NAME=ds-nature-ayur
      - MONGOURL=mongodb+srv://Heshan:Heshan123@cluster0.dyyifxu.mongodb.net/naturaayur?retryWrites=true&w=majority
      - JWT_SECRET=NAtureAyut2023LLcC
      - JWT_REFRESH_TOKEN=NAtureAyut2023LLcCREFRERESH
      - ADMIN_MAIL=natureayure@gmail.com
      - ADMIN_MAILAPP_PASSWORD=jtkgrcvpkpsjvuho
      - FRONTEND=http://localhost:3000
      - PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51Mud2bCdnivczi88IyelFBlmNOwCywXQWsUYbDCc7XjISenCaElNJjY3K4QAEWO50wdKFWgYJRIjUgHPKbcaB9T500SIdlAVHS
      - PUBLIC_STRIPE_SECRET_KEY=sk_test_51Mud2bCdnivczi886NjEi2yULVgdkuTqhbyYIqKBHTKmpuwWQGbJN6fTEOa5szpIcK9po23NuEAd4HySXIEykXkc00qsg3WyWh
      - PUBLIC_STRIPE_WEBHOOK_SECRET_KEY=whsec_9580fde0829c6d8586cebfd04aa12f398b20806b07517da5b21e6776f61fff01

networks:
  mern-app:
    driver: bridge
