apiVersion: v1
kind: Secret
metadata:
  name: mongo-sercret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy #value needs to be in base 64 if you are using opaque
  mongo-passsword: bW9uZ29wYXNzd29yZA==
